### ISSUE TITLE
Some Services are mixed up and will be shown in the wrong Hosts

### ISSUE THREAD

**Issue by uclara** [sni/Thruk#1024]
**Describe the bug**
After activating LMD with Thruk and Icinga2 as core some Services are mixed up and will be shown in the wrong Hosts

**Thruk Version**
Thruk version 2.34-2 and OMD version 3.30-labs-edition

**To Reproduce**
1. have a working setup with some Hosts and related Services (Icinga2 as core)
2. reading about the advantages of using LMD, specially to avoid known bugs of Icinga2
<https://www.thruk.org/documentation/lmd.html>
3. activate LMD
4. discovering that some Hosts have single services that doesn't belong to them. E.g a Host of type A contains a service of host type B
5. after deactivating LMD the structure of Host and related Services seems back to normal

**Expected behavior**
Having the same structure for hosts and their related services also after activating LMD

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 83.0.4103.106

**Additional context**

Ulli

**Comment by sni** [comment]
This is a know issue with Icinga2 which seem to return the hosts/services in random order while LMD expects them to be sorted.
There has been a workaround implemented in LMD here: https://github.com/sni/lmd/commit/5830ae19e6ebf96f92647f6ede4417f2f9e56e3a
So it should be fixed in any OMD daily since start of April.
