### ISSUE TITLE
Wrong Formating in Panorama-View

### ISSUE THREAD

**Issue by Mike-Sbg** [sni/Thruk#1180]
If you use a service-grid on all Browsers but Firefox and Internetexplorer the header with the service-names is to small

In FF and IE everything works fine ... also in Chrome until a few weeks ago

**Comment by sni** [comment]
Which chrome version is that?

**Comment by Mike-Sbg** [comment]
e.g. Chrome Version 103.0.5060

**Comment by Mike-Sbg** [comment]
If you tell me how, I could send you a screenshot

**Comment by themoonisacheese** [comment]
screenshot of the problem:
![image](https://user-images.githubusercontent.com/15526977/181251316-71565fa5-0606-4a3b-8d92-6bb4e7a0edd3.png)
Chrome Version 103.0.5060.134

the problem is not on firefox 102.0.1:
![image](https://user-images.githubusercontent.com/15526977/181251680-9019bd16-7eed-41f7-9f35-e86ba2353a49.png)

i took a look around chrome and ff devtools and found that the culprit is the class=vertical div used to display the text.
on firefox, correct (notice the 85.5px):
![image](https://user-images.githubusercontent.com/15526977/181253301-7b76a95c-4ad9-4487-b299-f7daf10f9d6c.png)

on chrome, incorrect (notice the 171 px):
![image](https://user-images.githubusercontent.com/15526977/181253560-b0516142-8663-4384-81f0-befcc01ac633.png)

inspect element editing the 171 to 85.5 yields the expected behavior.

it seems the server/js is trying to correct for browser behavior mismatch that doesn't exist anymore?
