### ISSUE TITLE
No refresh after changing the backend

### ISSUE THREAD

**Issue by tomaszdubiel18** [sni/Thruk#1192]
![obraz](https://user-images.githubusercontent.com/85760200/184931864-9839e8ba-b659-446f-b987-c69c9f7ec2a6.png)
Looking at the Thruk demo I'm not sure, but in my opinion the content of the page should refresh after selecting/deselecting the backend. Now clicking doesn't change anything, I need to refresh the whole page.

**Comment by sni** [comment]
Works for me. Toggling the buttons on demo.thruk.org ex. on the tac page, clearly changes the content. Which browser is that?
But i added a small countdown now which is triggered when changing the backends. You may need
to shift+reload once in order to refresh styles and javascript.

![image](https://user-images.githubusercontent.com/150844/185696018-62283a62-e658-4507-a2e3-dae790a1c5d1.png)

**Comment by tomaszdubiel18** [comment]
Why does it take so long? I didn't notice it happens after a while. I expected this to happen immediately after click. This countdown now explains everything, but still, if this has to be for some reason with delay, I would see it two times faster.

**Comment by sni** [comment]
It's 1.5 seconds delay. The reason is you have usually some more backends. The delay helps you click/deselect all those you want and not one by one with a reload in between.

**Comment by tomaszdubiel18** [comment]
Yeah, that makes sense now.
