### ISSUE TITLE
Going back to host/service details pages does not work

### ISSUE THREAD

**Issue by awiddersheim** [sni/Thruk#357]
If you navigate to the details page of a host/service (`extinfo.cgi?type=1` and `extinfo.cgi?type=2`) and then to some other page in Thruk (can be any page from what I've seen) and then hit back you'll get returned to a non-existant page. The URL only includes something similar to `#pnp_th2/1400593806/1400683806`.

This started occurring after upgrading from `1.82` to `1.84-2`. I rolled back to my previous `1.82` version and this issue did not occur. I can also reproduce on http://demo.thruk.org so I don't think it is an issue local to myself.

I am only able to reproduce using Chrome so far. Tried both firefox and IE and they seem to work fine.

I seem to remember some commits geared toward Chrome specifically dealing with cookie that were included in the `1.84` release but I could be wrong. Might be something to do with those though.

**Comment by taocnrut** [comment]
This is also happening to me with version 2.26-2 installed with OMD 2.90-labs-edition using both Chome and Firefox. It worked ok in 2.24 which was installed in OMD v2.80. It works when I revert to previous usage of  history.replaceState instead of history.pushState


`
--- templates/index.tt-original 2019-02-04 12:58:33.356829892 +0100
+++ templates/index.tt  2019-02-04 12:58:41.611804302 +0100
@@ -52,8 +52,8 @@
         var patt   = new RegExp('^' + get_host(), 'gi');
         newloc     = newloc.replace(patt, '');
         if('#'+newloc != window.location.hash) {
-            if(history.pushState) {
-                history.pushState({}, "", '#'+newloc);
+             if (history.replaceState) {
+                 history.replaceState({}, "", '#'+newloc);
             } else {
                 skipHashChange = skipHashChange + 1;
                 window.location.replace('#'+newloc);
`

**Comment by sni** [comment]
This should be fixed in the nightly builds already.
