### ISSUE TITLE
HA Thruk, cron jobs

### ISSUE THREAD

**Issue by GuusH** [sni/Thruk#445]
Hi,

As discussed in http://www.monitoring-portal.org/wbb/index.php?page=Thread&postID=212752#post212752 here's the Github issue to track this.

We're running multiple Thruk instances behind a load balancer in active/active mode. As mentioned in the documentation we've put /var/lib/thruk on a shared filesystem, so all nodes have concurrent read/write access to it. It's working pretty well, but we've noticed something odd with scheduled downtimes cron jobs. When you do something with scheduled downtimes, the cron stuff gets updated on the Thruk node you're currently connected to, but not on the other nodes. The cron jobs are actually installed for the www-data user, so they're in /var/spool/cron/crontabs/www-data (Ubuntu).
Until someone does something with scheduled downtimes on one of the other nodes, these cron settings do not get installed on that node. So after a while there's a bit of a mismatch happening between the various nodes. Also since the cronjobs are on multiple nodes, they fire on each node. Looks like our backend (Shinken) is clever enough to ignore any redundant commands, but it feels a bit weird.

**Comment by awiddersheim** [comment]
I have also found the approach Thruk takes for scheduled downtimes writing to cron jobs not ideal when it comes to HA situations. It is simple and works well for single server scenarios which are the vast majority and  why I am guessing it has not be changed.

 I run Thruk in an active/passive HA scenario so it is slightly different but here is what I do. I wrote two scripts to help. The first is a perl script that will take all of the downtimes being added by Thruk and create a single file with all of them in JSON. The second script is in python. I add it to my cron to run every night at midnight. It has some quick logic that will only allow it to run if it is the active node. Then it takes all the downtimes in the JSON file and adds them (if necessary).

A bit more work and some added complication but it has worked well for us. I can post the scripts if interested.

**Comment by GuusH** [comment]
That would certainly help, yes! Depending on the logic you've implemented, I can adapt / adjust that to use a lock file on the shared filesystem so it's only executed by the quickest Thruk node, whichever one that is. Thanks!

**Comment by awiddersheim** [comment]
Sure thing. Give me a bit and I'll throw it all up somewhere.

**Comment by awiddersheim** [comment]
Here are the scripts:

https://github.com/awiddersheim/thruk_downtimes

So the `downtime_extract.pl` is what gets run when Thruk would normally put data into these individual files and update the crontab. Rather than doing that, I transform that data into a single JSON file. Check out the config options necessary to have this run in `thruk_local.conf`.

Then `downtime_pump.py` is what gets run by `thruk.cron` each night at midnight. It reads that JSON file and schedules the downtimes for that day.

Ideally, Thruk would output the downtimes into something more inter operable like JSON natively. However, it uses a perl specific structure that can be hard for other languages other than perl to read. This is why the `downtime_extract.pl` stuff is needed.

I talked to @sni a bit about this problem. Probably low on his priority list since HA setups like ours aren't very common and he has added enough to Thruk to allow for me to plugin and handle things in my own specific way.

Hope it helps. Let me know if you have any questions.

**Comment by sni** [comment]
latest Thruk supports clusters, please give it a look.
