### ISSUE TITLE
IE11 Panorama grids

### ISSUE THREAD

**Issue by mariano-fiorentino** [sni/Thruk#646]
Hi,
i have a problem to visualize correctly Panorama View items under IE11. I tried with different X-UA-Compatible without success. Looking at the DOM and at the network stream, seems that thruk load correctly the request to get grid headers and data, but did't render them into the panel instead showing a gray box.
The problem is reproducible with the last version of thruk 2.10.
If i understood, the piece of software that manage the redendering of the data in the panel  is the callback function inside:

./plugins/plugins-available/panorama/root/js/panorama_js_panlet_grid.js

Do you have some fix for that problem?

Best Regards,

Mariano Fiorentino

**Comment by fullmetalucard** [comment]
Hi same problem here.
Running 2.06 version, we had troubles to visualize correctly some items in panorama view, only with IE 11.
With firefox browser, no problems encountered. So we upgraded to the latest 2.10 today, and added the useragentcompat option. The behavior si still the same, even if looking at the source code of the page, we are able to see "compatibility header". 
We even tried to set loglevel to debug, but we had no more interesting informations about it in thruk logs.
This problem is very annoying as our working environment doesn't allow us to use firefox..no escape from using it. What a pitty to not to be able to fully use such a useful tool, juste because of browser compatibility.
I know some other people who have the same problem. 
I guess this is very easy to reproduce with any IE 11 browser. From what I know, only pie charts and event log viewer widgets are affected by this behavior. Could you please take a look at this problem?

Thanks in advance for your help.

Kind regards,

**Comment by mariano-fiorentino** [comment]
I found the follow workaround. The problem is that thruk is been developed using extjs 4.1 that don't gave support to ie11. If you modifiy the extjs source of 

- thruk/plugins/plugins-available/panorama/root/extjs-4.1.1/ext-all-debug.js
- thruk/plugins/plugins-available/panorama/root/extjs-4.1.1/ext-all.js

Adding this line at the end:
`if (Object.hasOwnProperty.call(window, "ActiveXObject") && !window.ActiveXObject) { // is IE11
    Ext.apply(Ext, {
        isIE : true, // cosmetic, since it's false by default for IE11
        isIE11: true,
        ieVersion: 11
    });


    Ext.override(Ext.layout.container.Container, {
        getLayoutTargetSize : function() {
            var target = this.getTarget(),
                ret;


            if (target) {
                ret = target.getViewSize();


                // IE in will sometimes return a width of 0 on the 1st pass of getViewSize.
                // Use getStyleSize to verify the 0 width, the adjustment pass will then work properly
                // with getViewSize
                if ((Ext.isIE || Ext.isIE11) && ret.width == 0){
                    ret = target.getStyleSize();
                }


                ret.width -= target.getPadding('lr');
                ret.height -= target.getPadding('tb');
            }
            return ret;
        }
    });
}
`
Under IE11 the panorama view is correctly rendered. What still missed is some css alignment that is to fix.

**Comment by sni** [comment]
Could you please put this into a pull request if thats a working solution?
