### ISSUE TITLE
Disable host with its services

### ISSUE THREAD

**Issue by renard** [sni/Thruk#740]
I am using Thruk 2.14-2 with Naemon as provided by Consol.de (https://labs.consol.de/repo/stable/).

With the default install I try to disable one host (let's say `hplj2605dn`), on the Host configuration tab by click on *Disable this host temporarily* and applying the changes.

On the *Apply* menu I have following errors:
```
referenced host 'hplj2605dn' does not exist in printer.cfg:50
referenced host 'hplj2605dn' does not exist in printer.cfg:60
```

The question is how can I cascade the disable actions from hosts to services as well? 

Did I missed something?

Thanks in advance.

Cheers.

**Comment by sni** [comment]
Right now this is not possible. And i don't think it can be implemented easily since there is no way to remember which references should be reverted when the object will be activated again.
Disabling hosts works better if you assign the services against hostgroups and set the hostgroups list in the host itself.
