### ISSUE TITLE
Query: How many nagios backend can thruk accomodate?

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/Thruk#850]
Hi Sven,

Just wondering on how many nagios backends can thruk able to support?

Thanks!

**Comment by steaksauce-** [comment]
Presumably as many as your system can process, cache, etc...
Not sure if there's a hard number.

Would be fun to have an environment that can be easily reproduced monitoring ~1000 nodes or so (think containers) and do an experiment to see when it starts to bog down on a system with recommended specs (assuming there are recommended specs -- I can't remember off of the top of my head).

**Comment by sni** [comment]
There are no hard numbers. It depends mostly on the location and the connection of your backends. You can easily connect 20 backends which are on the same machine but it will get ugly if those 20 backends are all around the world with lousy connections.
Then LMD (https://thruk.org/documentation/lmd.html) comes handy and we operate setups with over 200 backends all around the globe and with LMD the limit is just cpu and memory, mostly memory since it offloads any connection issues and latencies.
