### ISSUE TITLE
reload command succeeded, but services are missing

### ISSUE THREAD

**Issue by hasifm2010** [sni/Thruk#989]
What could be the reason getting below error while saving BP?

"reload command succeeded, but services are missing"

**Comment by sni** [comment]
The reason is usually that thruk was able to write out the config file containing the hosts and services for the business process and was able to initiate the core reload command. After that it fetches hosts and services from the core to ensure the reload was successful and it seems like the core does not have those hosts and services. Most likely because it does not use those config files.

Check your configuration and make sure your core does read that file:
```
<Component Thruk::Plugin::BP>
    objects_save_file = /etc/naemon/conf.d/thruk_bp_generated.cfg
</Component>
```

**Comment by hasifm2010** [comment]
This issue was resolved by creating BP on corresponding sites... Thanks for your support.
